#!/usr/bin/env ruby

require 'tempfile'
# require rundeck-docker-plugin.rb because this file is named the same.
require File.expand_path(__FILE__)

begin
  tmpfile = Tempfile.new 'RundeckDockerPlugin'
  cmd = RundeckDockerPlugin.new(tmpfile).cmd

  if ENV['RD_JOB_LOGLEVEL'] == 'DEBUG'
    STDERR.puts ENV.select{|k,_| k =~ /^RD_/}
    STDERR.puts "Running command: #{cmd}"
  end

  raise "Command: #{cmd} failed." unless system cmd
rescue => err
  STDERR.puts "#{err.class}: #{err.message}"
  exit $? ? $?.exitstatus : 1
ensure
  tmpfile.close
  tmpfile.unlink
end
